"""fourth commit

Revision ID: 18e892452d97
Revises: 7c6af5df2615
Create Date: 2025-03-07 16:21:17.270087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e892452d97'
down_revision: Union[str, None] = '7c6af5df2615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commentlikes_user_id_fkey', 'commentlikes', type_='foreignkey')
    op.create_foreign_key(None, 'commentlikes', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'commentlikes', type_='foreignkey')
    op.create_foreign_key('commentlikes_user_id_fkey', 'commentlikes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
