"""v3 user new coloumn

Revision ID: b0da1c95964b
Revises: 83d8907e78a9
Create Date: 2025-01-23 15:20:18.966929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0da1c95964b'
down_revision: Union[str, None] = '83d8907e78a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('follower_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'follower_count')
    # ### end Alembic commands ###
